apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      project: akri
      protocol: http
      function: discovery
  template:
    metadata:
      labels:
        project: akri
        protocol: http
        function: discovery
      name: discovery
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: discovery
          image: [[IMAGE]]
          imagePullPolicy: Always
          args:
            - --device=http://device-1:8001
            - --device=http://device-2:8002
            - --device=http://device-3:8003
            - --device=http://device-4:8004
            - --device=http://device-5:8005
            - --device=http://device-6:8006
            - --device=http://device-7:8007
            - --device=http://device-8:8008
            - --device=http://device-9:8009
          ports:
            - name: http
              containerPort: 9999
