apiVersion: v1
kind: List
metadata:
  name: list
items:
{{- range int .Values.device.count | until }}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      id: akri-http-device
    name: {{ printf "%s:%02d" $.Values.device.name . }}
  spec:
    ports:
    - port: {{ $.Values.device.port }}
      protocol: TCP
      targetPort: 8080
    selector:
      function: device
      project: akri
      protocol: http
    type: ClusterIP
{{- end }}
