apiVersion: v1
kind: Service
metadata:
  labels:
    id: akri-http-discovery
  name: {{ .Values.discovery.name }}
spec:
  ports:
  - port: {{ .Values.discovery.port }}
    protocol: TCP
    targetPort: 9999
  selector:
    function: discovery
    project: akri
    protocol: http
  type: ClusterIP
