apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.discovery.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      project: akri
      protocol: http
      function: discovery
  template:
    metadata:
      labels:
        project: akri
        protocol: http
        function: discovery
      name: {{ .Values.discovery.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
        - name: discovery
          image: {{ printf "%s:%s" .Values.discovery.image.repository .Values.discovery.image.tag | quote }}
          imagePullPolicy: {{ .Values.discovery.image.pullPolicy }}
          args:
          {{- range int .Values.device.count | until }}
            - --device={{ printf "http://%s-%02d:%d" $.Values.device.name . $.Values.device.port }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9999
