apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-grpc-client-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      project: akri
      protocol: http
      function: client
      language: golang
  template:
    metadata:
      labels:
        project: akri
        protocol: http
        function: client
        language: golang
      name: http-grpc-client-rust
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: http-grpc-client-golang
          image: ghcr.io/dazwilkin/http-grpc-client-golang@sha256:ed046722281040f931b7221a10d5002d4f328a012232d01fd6c95db5069db2a5
          args:
            - --grpc_endpoint=http-svc:50051
