name: containers-devices

on:
  push:
    branches:
      - master

jobs:
  devices:
    name: devices
    runs-on: ubuntu-20.04
    env:
      REPO: dazwilkin/akri-http-devices
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: build-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/devices/Dockerfile
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          push: true
